app/models.py
from app import db, login_manager
from uuid import uuid4
from datetime import datetime
from werkzeug.security import generate_password_hash, check_password_hash
from .utilities import generate_random_uuid
from flask_login import UserMixin



@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

class User(db.Model, UserMixin):

    id = db.Column(db.String(36), default = generate_random_uuid, primary_key = True)
    username = db.Column(db.String(100), nullable = False)
    password_hash = db.Column(db.String(200), nullable = False)
    displayname = db.Column(db.String(150), nullable = False)
    emailaddress = db.Column(db.String(150), nullable = False)
    created = db.Column(db.DateTime(), default = datetime.now)
    updated = db.Column(db.DateTime(), nullable = True)
    last_online = db.Column(db.DateTime(), nullable = True)
    country = db.Column(db.String(100), nullable = False)
    date_of_birth = db.Column(db.DateTime(), nullable = True)

    rooms = db.relationship("Room", backref = "owner")

    @property
    def password(self):
        raise AttributeError("Cant access password directly")
    
    @password.setter
    def password(self, value):
        self.password_hash = generate_password_hash(value)
    
    @property
    def avatar_url(self):
        return "https://ui-avatars.com/api/?name={0}&background=random&rounded=true&size=96".format(self.emailaddress)
    
    @avatar_url.setter
    def avatar_url(self, value):
        raise AttributeError("Cant set avatar url")
    
    def verify_password(self, value):
        return check_password_hash(self.password_hash, value)
    
    def update_settings(self):
        self.updated = datetime.now()
    
    def ping(self):
        self.last_online = datetime.now()

class Room(db.Model):
    
    id = db.Column(db.String(36), default = uuid4, primary_key = True)
    name = db.Column(db.String(100), nullable = False)
    members = db.Column(db.Integer(), default = 1)
    created = db.Column(db.DateTime(), default = datetime.now)
    updated = db.Column(db.DateTime(), nullable = True)
    documentId = db.Column(db.String(), nullable = True)

    ownerId = db.Column(db.ForeignKey('user.id'), nullable = False)

app/__init__.py
from config import config_dict
from flask import Flask
from dotenv import load_dotenv
import os
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager

db = SQLAlchemy()
migrate = Migrate()
login_manager = LoginManager()

def redirect_home():
    #* Redirect to home page
    
    from flask import redirect, url_for
    return redirect(url_for('main.home'))

load_dotenv()

def create_app(config = os.getenv('APP_CONFIG')):
    
    #* Create app and add config
    app = Flask(__name__)
    app.config.from_object(config_dict[config])

    #* Initialize extensions
    db.init_app(app)
    migrate.init_app(app, db)
    login_manager.init_app(app)

    #* register blueprints
    from .users import user_blueprint
    app.register_blueprint(blueprint = user_blueprint, url_prefix = '/users')

    from .main import main_blueprint
    app.register_blueprint(blueprint = main_blueprint, url_prefix = '/main')

    from .room import room_blueprint
    app.register_blueprint(blueprint = room_blueprint, url_prefix = '/room')

    from .auth import auth_blueprint
    app.register_blueprint(blueprint = auth_blueprint, url_prefix = '/auth')

    app.add_url_rule('/', 'home', redirect_home)

    from app import models
    from app import documents

    return app

app/main/__init__.py
from flask import Blueprint

main_blueprint = Blueprint("main", __name__)

from . import routes 

app/main/routes.py
from . import main_blueprint
from flask import render_template

@main_blueprint.route('/')
def home():
    return render_template('main/home.html')

app/room/__init__.py
from flask import Blueprint

room_blueprint = Blueprint("room", __name__)

from . import routes

app/room/routes.py
from . import room_blueprint
from flask import render_template

@room_blueprint.route('/')
def all_rooms():
    return render_template('room/rooms.html')

app/users/__init__.py
from flask import Blueprint

user_blueprint = Blueprint('user', __name__)

from . import routes

app/users/routes.py
from . import user_blueprint


@user_blueprint.route("/")
def home():
    return '<h1> Hello World </h1>'

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>LiveSketch - {% block title %}
        
    {% endblock %}</title>
    <link rel="stylesheet" href="{{url_for('static', filename = 'css/bulma.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename = 'css/styles.css')}}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma-steps@2.1.1/dist/css/bulma-steps.min.css">
  </head>

  <body>
    <nav class="navbar glass" role="navigation" aria-label="main navigation" style="border-radius: 1px;">
      <div class="navbar-brand">
        <a class="navbar-item" href="https://bulma.io">
          <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28">
        </a>

        <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false"
          data-target="navbarBasicExample">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>

      <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
          <a class="navbar-item" href="{{url_for('main.home')}}">
            Home
          </a>
          <a href="{{url_for('room.all_rooms')}}" class="navbar-item">
            Rooms
          </a>
          <a href="{{url_for('room.all_rooms')}}" class="navbar-item">
            Users
          </a>
          <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-link">
              More
            </a>
            <div class="navbar-dropdown glass">
              <a class="navbar-item glass">
                About
              </a>
              <a class="navbar-item glass mt-2">
                Jobs
              </a>
              <a class="navbar-item glass mt-2">
                Contact
              </a>
              <hr class="navbar-divider">
              <a class="navbar-item glass mt-2">
                Report an issue
              </a>
            </div>
          </div>
        </div>
        {% if current_user.is_authenticated %}
          
        <div class="navbar-end">
          <div class="navbar-item">
            <img src="{{current_user.avatar_url}}" alt="">
          </div>
          <div class="navbar-item mr-5">
            <p class="title is-5">{{ current_user.username }}</p>
          </div>
          <div class="navbar-item">
            <a href="{{url_for('auth.logout')}}" class="button is-light mr-5"><strong>Logout</strong></a>
          </div>
        </div>
        {% else %}
          
        <div class="navbar-end">
          <div class="navbar-item">
            <div class="buttons">
              <a class="button is-primary" href="{{url_for('auth.signup')}}">
                <strong>Sign up</strong>
              </a>
              <a class="button is-light" href="{{url_for('auth.login')}}">
                Log in
              </a>
            </div>
          </div>
        </div>
        {% endif %}
      </div>
    </nav>
    <!-- TODO Finalize pallete -->
    {% with messages = get_flashed_messages(with_categories = true)  %}
      {% if messages %}

        {% for category, message in messages %}
          <div class="notification glass-is-{{category}} has-text-centered">
            <button class="delete"></button>
            {{ message }}
          </div>
        {% endfor %}
        
      {% endif %}
      
    {% endwith %}
    {% block content %}
      
    {% endblock %}
  </body>
  <script src="{{url_for('static', filename = 'js/toggler.js')}}"></script>
  <script src="{{url_for('static', filename = 'js/bulma-steps.js')}}"></script>
</html>

app/templates/main/home.html
{% extends './base.html' %}

{% block title %}
Home
{% endblock %}

{% block content %}
<section class="hero is-fullheight">
  <div class="hero-body">
    <div class="container has-text-centered">
      <h1 class="title is-1" style="font-size: 5vw;">
        Livesketch
      </h1>
      <h2 class="subtitle is-3" style="font-size: 3.1vw;">
        Draw together, anywhere
      </h2>
      <a href="{{url_for('auth.signup')}}" class="button is-primary is-large">Collaborate Now</a>
    </div>
  </div>
</section>

<footer class="footer glass" style="border-radius: 0px;">
  <div class="content has-text-centered">
    <p>
      <strong>Livesketch</strong> by <a href="">Akinfenwa Ezekiel</a>. The source code is licensed
      <a href="http://opensource.org/licenses/mit-license.php">MIT</a>. The website content
      is licensed <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY NC SA 4.0</a>.
    </p>
  </div>
</footer>

<script>
  typewriterConfig = ["Livesketch", true]
  typewriter();
</script>
{% endblock %}

app/templates/room/rooms.html
{% extends './base.html' %}
{% block title %}
Rooms
{% endblock %}

{% block content %}
<div class="section container box mt-4 glass">
    <div class="columns">
        <div class="column is-one-fifth">
            <h1 class="title">All Rooms</h1>
        </div>
        <div class="column"></div>
        <div class="column">
            <div class="field">
                <label class="label">
                    Search Room</label>
                <div class="control">
                    <input class="input" type="text" placeholder="Enter room">
                </div>
            </div>
            <a href="" class="button is-primary">Search</a>
        </div>
    </div>
</div>

<section class="section p-4">

    <div class="container box glass mt-6 mb-6">
        <div class="columns is-multiline">
            <div class="column">
                <div class="card">
                    <div class="card-image">
                        <figure class="image is-4by3">
                            <img src="https://bulma.io/images/placeholders/1280x960.png" alt="Room avatar image">
                        </figure>
                    </div>
                    <div class="card-content">
                        <div class="media">
                            <div class="media-content">
                                <p class="title is-4">Room name</p>
                                <p class="subtitle is-6">@roomId</p>
                            </div>
                        </div>

                        <div class="content">
                            What is this nice room all about?
                            . <a href="#" class="tag is-medium is-primary is-rounded">#css</a> <a href="#"
                                class="tag is-medium is-primary is-rounded">#responsive</a>
                            <br>
                            <p>Created by <a href="">@username not displayname</a></p>
                            <div class="field">
                                <a href="" class="button is-medium is-info">Visit Room</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <hr>
        </div>

        <div class="box">
            <nav class="pagination" role="navigation" aria-label="pagination">
                <a class="pagination-previous">Previous</a>
                <a class="pagination-next">Next page</a>
                <ul class="pagination-list">
                    <li>
                        <a class="pagination-link" aria-label="Goto page 1">1</a>
                    </li>
                    <li>
                        <span class="pagination-ellipsis">&hellip;</span>
                    </li>
                    <li>
                        <a class="pagination-link" aria-label="Goto page 45">45</a>
                    </li>
                    <li>
                        <a class="pagination-link is-current" aria-label="Page 46" aria-current="page">46</a>
                    </li>
                    <li>
                        <a class="pagination-link" aria-label="Goto page 47">47</a>
                    </li>
                    <li>
                        <span class="pagination-ellipsis">&hellip;</span>
                    </li>
                    <li>
                        <a class="pagination-link" aria-label="Goto page 86">86</a>
                    </li>
                </ul>
            </nav>

        </div>
    </div>
</section>
{% endblock %}